CREATE TABLE IF NOT EXISTS genre (
    id           INT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name   varchar(50)
);

CREATE TABLE IF NOT EXISTS friendship (
    id_friends  INT,
    id_users    INT,
    status      BOOLEAN
);

CREATE TABLE IF NOT EXISTS users (
	id       INT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email    varchar(50)    NOT NULL,
	login    varchar(50)    NOT NULL,
	name     varchar(50),
	birthday TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id              INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(50)     NOT NULL,
    description     varchar(200),
    release_date    TIMESTAMP       NOT NULL,
    duration        INT             NOT NULL,
    mpa             varchar(20)     NOT NULL
);

CREATE TABLE IF NOT EXISTS films_users_relationship (
    id_users INT REFERENCES users (id),
    id_films INT REFERENCES films (id)
);

CREATE TABLE IF NOT EXISTS genres_films (
    id_films INT REFERENCES films (id),
    id_genres INT REFERENCES genre (id)
);

